### ISSUE TITLE
Update jupyterlab version and fix visualization in incore-lab

### ISSUE THREAD

**Issue by ywkim312** [IN-CORE/incore-lab#56]
The incore-lab's jupyterlab version has not been updated for a while. The version of jupyterlab in incore-lab should be updated. Also, there is problems in visualization in incore-lab that it is not able to show some overlaying layers. Currently, the problem is suppressed by installing jupyterlab 3.6.3 again to have correct working status of ipyleaflet in the jupyterlab docker image, and this makes the incore-lab docker image has two layers of jupyterlab in the docker image, making the image size bigger and redundant. The original jupyterlab image also has the ipyleaflet installed, but somehow, the visualization fails even though the docker images original jupyterlab version is the same that is 3.6.3 or other. So the incore-lab should have only one layer of jupyterlab in the image and the visualization of the ipyleaflet must work.

**Comment by ywkim312** [comment]
To test leaftlet error, simply run the pyincore-viz-example.ipynb in incore-lab

If it is working, it will look like this
![image](https://github.com/IN-CORE/incore-lab/assets/12547573/05b105b9-831a-4b91-8a5f-029be4712f3e)

**Comment by ywkim312** [comment]
If it doesn't work, it will be looking like this
![image](https://github.com/IN-CORE/incore-lab/assets/12547573/e695c25e-9ea5-483d-abd4-c1be858045d3)

**Comment by ywkim312** [comment]
If it works, it will be looking like this
![image](https://github.com/IN-CORE/incore-lab/assets/12547573/0b0d8753-a1de-41e0-ae0a-f64fb2ae6cbe)

**Comment by Vismayak** [comment]
![Image](https://github.com/IN-CORE/incore-lab/assets/16596733/055e1b23-9776-434b-bf14-308ad31c004c)

I am confused, the notebook when  in hub is working, does this mean the issue has been tackled?

In addition, I  recreated the image with  jupyterlab version 3.6.5 and it also seems to work

**Comment by Vismayak** [comment]
I have committed a branch with the updated image

**Comment by ywkim312** [comment]
> ![Image](https://user-images.githubusercontent.com/16596733/251272676-055e1b23-9776-434b-bf14-308ad31c004c.png)
> 
> I am confused, the notebook when in hub is working, does this mean the issue has been tackled?
> 
> In addition, I recreated the image with jupyterlab version 3.6.5 and it also seems to work

Yes it works in incore lab since it has newly installed jupyterlab 3.6.3 in it. Like explained above, it has two jupyterlabs installed in single image in different layers. The base image already contains one and it had one more jupytetlab installed in other layer by Dockerfile to make visualization to work. So, please try yo make the visualization to work without installing the additional jupytetlab in the container image. Or you can do whatever but we only want to have a single jupytetlab in the docker container layers
