### ISSUE TITLE
Resolve issues from using mamba or libmamba solver to install pyincore

### ISSUE THREAD

**Issue by Vismayak** [IN-CORE/incore-lab#68]
![image](https://github.com/IN-CORE/incore-lab/assets/16596733/a271919f-7682-4bce-83c2-b46846482435)

The screenshot is from running the pyincore-viz notebook in a jupyter-lab image created with the mamba installation

**Comment by robkooper** [comment]
can you add some information that shows the libraries installed by conda and mamba?

**Comment by robkooper** [comment]
this is a duplicate of: https://github.com/IN-CORE/pyincore/issues/409
